title: Carmel WENGA # your name (or website title) here
logo: "/images/profil.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD. Candidate in Machine Learning, <br>
  Applied Reseach Engineer, <br>
  Data Scientist,<br>
  Software Developer,<br>
  Nzhinusoft AI Reseach.
  <hr>
  My name is Carmel WENGA. I am a PhD student in machine learning applied 
  to recommendation systems. I work as an applied research engineer and Software Developer
  at Nzhinusoft and my job is to integrate and manage machine learning solutions 
  in Nzhinusoft's projects. I'm passionate about machine learning, 
  artificial intelligence, software development and new technology.
   
  <br><br>
  <a href="https://www.linkedin.com/in/carmel-wenga-871876178/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
